### ISSUE TITLE
Find a way to maximize GPU utilization

### ISSUE THREAD

**Issue by justheuristic** [yandexdataschool/AgentNet#14]
Subj. Right now it's evaluated as 30%

Find if there are some profiling tools or tips for optimization. Find out how exactly are shared_values stored (on what side?)

**Comment by BladeCarrier** [comment]
Originally caused by small network & low batch size; now 50~100%, avg ~80; Still a lot to be done

**Comment by justheuristic** [comment]
not actual. GPU-efficient since June or something
