### ISSUE TITLE
Minimal initial example.

### ISSUE THREAD

**Issue by arogozhnikov** [yandexdataschool/AgentNet#53]
I think it's hard to dive into AgentNet mostly because of too complex initial example.

Possible options:
 - simplify boolean reasoning notebook  (and have at most couple of plots).
 - come up with other 'trivial problem', I suppose that addition being considered as map 2 sequences -> sequence is fairly trivial to learn and very simple to demonstrate the progress of algorithm (by highlighting mistakes).

**Comment by justheuristic** [comment]
Simplified quite a bit. Any comments?
![atari tutorial](https://github.com/yandexdataschool/AgentNet/blob/develop/examples/Playing%20Atari%20with%20Deep%20Reinforcement%20Learning%20%28OpenAI%20Gym%29.ipynb)

**Comment by iaroslav-ai** [comment]
I agree with arogozhnikov. The repo looks really interesting, but big examples make it hard to comprehend [in limited spare time] how things work.

**Comment by justheuristic** [comment]
Thanks for the feedback!
We are currently working on simplification of the examples (and perhaps "a bitesize demo" with absolute minimum of code)

**Comment by justheuristic** [comment]
https://github.com/yandexdataschool/AgentNet/pull/65
