### ISSUE TITLE
Automated tests on convergence

### ISSUE THREAD

**Issue by arogozhnikov** [yandexdataschool/AgentNet#54]
Maybe use reasoning problem as s simple test of algorithm convergence?

**Comment by justheuristic** [comment]
I am sorry, but what do you mean by "automated tests"?
Check whether algorithm didn't diverge? (`not np.any(np.isnan(loss))`)
Check whether algorithm has flat learning curve ( correlation(loss,time) ~ 0 over last N sessions)
Check whether algorithm has state of the art performance? (idk)

**Comment by arogozhnikov** [comment]
Error falls below threshold at least one during n iterations is good enough for tests. (this is not convergence, sorry).

**Comment by justheuristic** [comment]
https://github.com/yandexdataschool/AgentNet/pull/67
