### ISSUE TITLE
Brief outline of modules

### ISSUE THREAD

**Issue by arogozhnikov** [yandexdataschool/AgentNet#77]
Would be nice to have it either on the main page or in /AgentNet to understand what those are responsible for.

**Comment by justheuristic** [comment]
TY for request, will do in a day or two.

**Comment by justheuristic** [comment]
Would that suffice?
http://agentnet.readthedocs.io/en/develop/user/whats_what.html#agentnet-agent

**Comment by justheuristic** [comment]
Did i understand you correctly?
http://agentnet.readthedocs.io/en/develop/user/whats_what.html

**Comment by arogozhnikov** [comment]
@justheuristic 

well, I just expected to have a small list :) 

But since you've written such a detailed version,  I think it is cool.
