### ISSUE TITLE
batch_size parameter is wierd

### ISSUE THREAD

**Issue by bestxolodec** [yandexdataschool/AgentNet#95]
[batch_size parameter](https://github.com/yandexdataschool/AgentNet/blob/master/agentnet/agent/mdp_agent.py#L360-L361) needs clarifications. 
Even if i don't provide any `initial_*` params, my bach size is completely ignored. 
The sentence  in the docs 
`[batch_size is] irrelevant if there's at least one input or if you manually set any initial_*.` 
does not provide sufficient explanation and depth  of `recurrence.py` seems even less friendly to understand why is `batch_size` ignored.

**Comment by justheuristic** [comment]
That's entirely correct, it is also ignored if you set experience_replay=True (and i am to blame for not updating.
Fixed in https://github.com/yandexdataschool/AgentNet/commit/75c1d582d00a51551d918e12c3d5c106e838755d
